app:
  message: This is the properties file for the ${spring.application.name} specific to TEST Enveroment
api:
  security:
    enable-https: false
spring:
  datasource:
    url: jdbc:h2:mem:testdb;IFEXISTS=FALSE;
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/master.xml