app:
  message: This is the properties file for the ${spring.application.name} specific to PROD Enveroment
api:
  security:
    enable-https: false
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jadira:
        usertype:
          autoRegisterUserTypes: true
  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  liquibase:
    change-log: classpath:db/master.xml